/*
 * Gestão de Contratos
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Entidade representando um cancelamento de um contrato.
 */
@ApiModel(description = "Entidade representando um cancelamento de um contrato.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-16T17:43:45.741Z")
public class CancelamentoContratoResponse {
  @SerializedName("contrato")
  private String contrato = null;

  @SerializedName("mensagem")
  private String mensagem = null;

  @SerializedName("comprovante")
  private String comprovante = null;

  public CancelamentoContratoResponse contrato(String contrato) {
    this.contrato = contrato;
    return this;
  }

   /**
   * Código do contrato.
   * @return contrato
  **/
  @ApiModelProperty(value = "Código do contrato.")
  public String getContrato() {
    return contrato;
  }

  public void setContrato(String contrato) {
    this.contrato = contrato;
  }

  public CancelamentoContratoResponse mensagem(String mensagem) {
    this.mensagem = mensagem;
    return this;
  }

   /**
   * Mensagem do retorno do cancelamento.
   * @return mensagem
  **/
  @ApiModelProperty(value = "Mensagem do retorno do cancelamento.")
  public String getMensagem() {
    return mensagem;
  }

  public void setMensagem(String mensagem) {
    this.mensagem = mensagem;
  }

  public CancelamentoContratoResponse comprovante(String comprovante) {
    this.comprovante = comprovante;
    return this;
  }

   /**
   * Comprovante de Cancelamento no seguinte formato.
   * @return comprovante
  **/
  @ApiModelProperty(value = "Comprovante de Cancelamento no seguinte formato.")
  public String getComprovante() {
    return comprovante;
  }

  public void setComprovante(String comprovante) {
    this.comprovante = comprovante;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CancelamentoContratoResponse cancelamentoContratoResponse = (CancelamentoContratoResponse) o;
    return Objects.equals(this.contrato, cancelamentoContratoResponse.contrato) &&
        Objects.equals(this.mensagem, cancelamentoContratoResponse.mensagem) &&
        Objects.equals(this.comprovante, cancelamentoContratoResponse.comprovante);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contrato, mensagem, comprovante);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CancelamentoContratoResponse {\n");
    
    sb.append("    contrato: ").append(toIndentedString(contrato)).append("\n");
    sb.append("    mensagem: ").append(toIndentedString(mensagem)).append("\n");
    sb.append("    comprovante: ").append(toIndentedString(comprovante)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

