/*
 * Gestão de Contratos
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Entidade representando uma parcela de um contrato, para a operação de recuperação de contratos.
 */
@ApiModel(description = "Entidade representando uma parcela de um contrato, para a operação de recuperação de contratos.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-16T17:43:45.741Z")
public class GetContratosParcelaResponse {
  @SerializedName("numeroParcela")
  private String numeroParcela = null;

  @SerializedName("dataVencimento")
  private String dataVencimento = null;

  @SerializedName("PMT")
  private Double PMT = null;

  @SerializedName("numeroDiasAtraso")
  private Integer numeroDiasAtraso = null;

  @SerializedName("percentualMulta")
  private Double percentualMulta = null;

  @SerializedName("valorMulta")
  private Double valorMulta = null;

  @SerializedName("percentualJurosAtraso")
  private Double percentualJurosAtraso = null;

  @SerializedName("valorJurosAtraso")
  private Double valorJurosAtraso = null;

  @SerializedName("valorIOFAtraso")
  private Double valorIOFAtraso = null;

  @SerializedName("valorDescontos")
  private Double valorDescontos = null;

  @SerializedName("despesas")
  private Double despesas = null;

  @SerializedName("valorSaldoParcela")
  private Double valorSaldoParcela = null;

  public GetContratosParcelaResponse numeroParcela(String numeroParcela) {
    this.numeroParcela = numeroParcela;
    return this;
  }

   /**
   * Número da parcela.
   * @return numeroParcela
  **/
  @ApiModelProperty(value = "Número da parcela.")
  public String getNumeroParcela() {
    return numeroParcela;
  }

  public void setNumeroParcela(String numeroParcela) {
    this.numeroParcela = numeroParcela;
  }

  public GetContratosParcelaResponse dataVencimento(String dataVencimento) {
    this.dataVencimento = dataVencimento;
    return this;
  }

   /**
   * Data de vencimento da parcela.
   * @return dataVencimento
  **/
  @ApiModelProperty(value = "Data de vencimento da parcela.")
  public String getDataVencimento() {
    return dataVencimento;
  }

  public void setDataVencimento(String dataVencimento) {
    this.dataVencimento = dataVencimento;
  }

  public GetContratosParcelaResponse PMT(Double PMT) {
    this.PMT = PMT;
    return this;
  }

   /**
   * Código da parcela.
   * @return PMT
  **/
  @ApiModelProperty(value = "Código da parcela.")
  public Double getPMT() {
    return PMT;
  }

  public void setPMT(Double PMT) {
    this.PMT = PMT;
  }

  public GetContratosParcelaResponse numeroDiasAtraso(Integer numeroDiasAtraso) {
    this.numeroDiasAtraso = numeroDiasAtraso;
    return this;
  }

   /**
   * Número de dias em atraso.
   * @return numeroDiasAtraso
  **/
  @ApiModelProperty(value = "Número de dias em atraso.")
  public Integer getNumeroDiasAtraso() {
    return numeroDiasAtraso;
  }

  public void setNumeroDiasAtraso(Integer numeroDiasAtraso) {
    this.numeroDiasAtraso = numeroDiasAtraso;
  }

  public GetContratosParcelaResponse percentualMulta(Double percentualMulta) {
    this.percentualMulta = percentualMulta;
    return this;
  }

   /**
   * Valor do percentual de multa.
   * @return percentualMulta
  **/
  @ApiModelProperty(value = "Valor do percentual de multa.")
  public Double getPercentualMulta() {
    return percentualMulta;
  }

  public void setPercentualMulta(Double percentualMulta) {
    this.percentualMulta = percentualMulta;
  }

  public GetContratosParcelaResponse valorMulta(Double valorMulta) {
    this.valorMulta = valorMulta;
    return this;
  }

   /**
   * Valor da multa.
   * @return valorMulta
  **/
  @ApiModelProperty(value = "Valor da multa.")
  public Double getValorMulta() {
    return valorMulta;
  }

  public void setValorMulta(Double valorMulta) {
    this.valorMulta = valorMulta;
  }

  public GetContratosParcelaResponse percentualJurosAtraso(Double percentualJurosAtraso) {
    this.percentualJurosAtraso = percentualJurosAtraso;
    return this;
  }

   /**
   * Valor do percentual de juros de atraso.
   * @return percentualJurosAtraso
  **/
  @ApiModelProperty(value = "Valor do percentual de juros de atraso.")
  public Double getPercentualJurosAtraso() {
    return percentualJurosAtraso;
  }

  public void setPercentualJurosAtraso(Double percentualJurosAtraso) {
    this.percentualJurosAtraso = percentualJurosAtraso;
  }

  public GetContratosParcelaResponse valorJurosAtraso(Double valorJurosAtraso) {
    this.valorJurosAtraso = valorJurosAtraso;
    return this;
  }

   /**
   * Valor de juros de atraso.
   * @return valorJurosAtraso
  **/
  @ApiModelProperty(value = "Valor de juros de atraso.")
  public Double getValorJurosAtraso() {
    return valorJurosAtraso;
  }

  public void setValorJurosAtraso(Double valorJurosAtraso) {
    this.valorJurosAtraso = valorJurosAtraso;
  }

  public GetContratosParcelaResponse valorIOFAtraso(Double valorIOFAtraso) {
    this.valorIOFAtraso = valorIOFAtraso;
    return this;
  }

   /**
   * Valor do IOF de atraso.
   * @return valorIOFAtraso
  **/
  @ApiModelProperty(value = "Valor do IOF de atraso.")
  public Double getValorIOFAtraso() {
    return valorIOFAtraso;
  }

  public void setValorIOFAtraso(Double valorIOFAtraso) {
    this.valorIOFAtraso = valorIOFAtraso;
  }

  public GetContratosParcelaResponse valorDescontos(Double valorDescontos) {
    this.valorDescontos = valorDescontos;
    return this;
  }

   /**
   * Valor dos descontos.
   * @return valorDescontos
  **/
  @ApiModelProperty(value = "Valor dos descontos.")
  public Double getValorDescontos() {
    return valorDescontos;
  }

  public void setValorDescontos(Double valorDescontos) {
    this.valorDescontos = valorDescontos;
  }

  public GetContratosParcelaResponse despesas(Double despesas) {
    this.despesas = despesas;
    return this;
  }

   /**
   * Valor de despesas.
   * @return despesas
  **/
  @ApiModelProperty(value = "Valor de despesas.")
  public Double getDespesas() {
    return despesas;
  }

  public void setDespesas(Double despesas) {
    this.despesas = despesas;
  }

  public GetContratosParcelaResponse valorSaldoParcela(Double valorSaldoParcela) {
    this.valorSaldoParcela = valorSaldoParcela;
    return this;
  }

   /**
   * Valor do saldo total da parcela.
   * @return valorSaldoParcela
  **/
  @ApiModelProperty(value = "Valor do saldo total da parcela.")
  public Double getValorSaldoParcela() {
    return valorSaldoParcela;
  }

  public void setValorSaldoParcela(Double valorSaldoParcela) {
    this.valorSaldoParcela = valorSaldoParcela;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetContratosParcelaResponse getContratosParcelaResponse = (GetContratosParcelaResponse) o;
    return Objects.equals(this.numeroParcela, getContratosParcelaResponse.numeroParcela) &&
        Objects.equals(this.dataVencimento, getContratosParcelaResponse.dataVencimento) &&
        Objects.equals(this.PMT, getContratosParcelaResponse.PMT) &&
        Objects.equals(this.numeroDiasAtraso, getContratosParcelaResponse.numeroDiasAtraso) &&
        Objects.equals(this.percentualMulta, getContratosParcelaResponse.percentualMulta) &&
        Objects.equals(this.valorMulta, getContratosParcelaResponse.valorMulta) &&
        Objects.equals(this.percentualJurosAtraso, getContratosParcelaResponse.percentualJurosAtraso) &&
        Objects.equals(this.valorJurosAtraso, getContratosParcelaResponse.valorJurosAtraso) &&
        Objects.equals(this.valorIOFAtraso, getContratosParcelaResponse.valorIOFAtraso) &&
        Objects.equals(this.valorDescontos, getContratosParcelaResponse.valorDescontos) &&
        Objects.equals(this.despesas, getContratosParcelaResponse.despesas) &&
        Objects.equals(this.valorSaldoParcela, getContratosParcelaResponse.valorSaldoParcela);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroParcela, dataVencimento, PMT, numeroDiasAtraso, percentualMulta, valorMulta, percentualJurosAtraso, valorJurosAtraso, valorIOFAtraso, valorDescontos, despesas, valorSaldoParcela);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetContratosParcelaResponse {\n");
    
    sb.append("    numeroParcela: ").append(toIndentedString(numeroParcela)).append("\n");
    sb.append("    dataVencimento: ").append(toIndentedString(dataVencimento)).append("\n");
    sb.append("    PMT: ").append(toIndentedString(PMT)).append("\n");
    sb.append("    numeroDiasAtraso: ").append(toIndentedString(numeroDiasAtraso)).append("\n");
    sb.append("    percentualMulta: ").append(toIndentedString(percentualMulta)).append("\n");
    sb.append("    valorMulta: ").append(toIndentedString(valorMulta)).append("\n");
    sb.append("    percentualJurosAtraso: ").append(toIndentedString(percentualJurosAtraso)).append("\n");
    sb.append("    valorJurosAtraso: ").append(toIndentedString(valorJurosAtraso)).append("\n");
    sb.append("    valorIOFAtraso: ").append(toIndentedString(valorIOFAtraso)).append("\n");
    sb.append("    valorDescontos: ").append(toIndentedString(valorDescontos)).append("\n");
    sb.append("    despesas: ").append(toIndentedString(despesas)).append("\n");
    sb.append("    valorSaldoParcela: ").append(toIndentedString(valorSaldoParcela)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

