/*
 * Gestão de Contratos
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SituacaoParcela;
import java.io.IOException;

/**
 * Entidade representando uma parcela de um contrato na saida da operação de recuperação de parcelas de um contrato.
 */
@ApiModel(description = "Entidade representando uma parcela de um contrato na saida da operação de recuperação de parcelas de um contrato.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-16T17:43:45.741Z")
public class GetParcelasParcelaResponse {
  @SerializedName("codigoContrato")
  private String codigoContrato = null;

  @SerializedName("valorPago")
  private Double valorPago = null;

  @SerializedName("numeroParcela")
  private Double numeroParcela = null;

  @SerializedName("dataPagamento")
  private String dataPagamento = null;

  @SerializedName("operador")
  private String operador = null;

  @SerializedName("NSU")
  private String NSU = null;

  @SerializedName("dataVencimento")
  private String dataVencimento = null;

  @SerializedName("PMT")
  private Double PMT = null;

  @SerializedName("valorSaldoParcela")
  private Double valorSaldoParcela = null;

  @SerializedName("situacao")
  private SituacaoParcela situacao = null;

  public GetParcelasParcelaResponse codigoContrato(String codigoContrato) {
    this.codigoContrato = codigoContrato;
    return this;
  }

   /**
   * Código do contrato.
   * @return codigoContrato
  **/
  @ApiModelProperty(value = "Código do contrato.")
  public String getCodigoContrato() {
    return codigoContrato;
  }

  public void setCodigoContrato(String codigoContrato) {
    this.codigoContrato = codigoContrato;
  }

  public GetParcelasParcelaResponse valorPago(Double valorPago) {
    this.valorPago = valorPago;
    return this;
  }

   /**
   * Valor pago.
   * @return valorPago
  **/
  @ApiModelProperty(value = "Valor pago.")
  public Double getValorPago() {
    return valorPago;
  }

  public void setValorPago(Double valorPago) {
    this.valorPago = valorPago;
  }

  public GetParcelasParcelaResponse numeroParcela(Double numeroParcela) {
    this.numeroParcela = numeroParcela;
    return this;
  }

   /**
   * Número da parcela paga.
   * @return numeroParcela
  **/
  @ApiModelProperty(value = "Número da parcela paga.")
  public Double getNumeroParcela() {
    return numeroParcela;
  }

  public void setNumeroParcela(Double numeroParcela) {
    this.numeroParcela = numeroParcela;
  }

  public GetParcelasParcelaResponse dataPagamento(String dataPagamento) {
    this.dataPagamento = dataPagamento;
    return this;
  }

   /**
   * Data do pagamento.
   * @return dataPagamento
  **/
  @ApiModelProperty(value = "Data do pagamento.")
  public String getDataPagamento() {
    return dataPagamento;
  }

  public void setDataPagamento(String dataPagamento) {
    this.dataPagamento = dataPagamento;
  }

  public GetParcelasParcelaResponse operador(String operador) {
    this.operador = operador;
    return this;
  }

   /**
   * Código do operador.
   * @return operador
  **/
  @ApiModelProperty(value = "Código do operador.")
  public String getOperador() {
    return operador;
  }

  public void setOperador(String operador) {
    this.operador = operador;
  }

  public GetParcelasParcelaResponse NSU(String NSU) {
    this.NSU = NSU;
    return this;
  }

   /**
   * Número sequencial único.
   * @return NSU
  **/
  @ApiModelProperty(value = "Número sequencial único.")
  public String getNSU() {
    return NSU;
  }

  public void setNSU(String NSU) {
    this.NSU = NSU;
  }

  public GetParcelasParcelaResponse dataVencimento(String dataVencimento) {
    this.dataVencimento = dataVencimento;
    return this;
  }

   /**
   * Data de vencimento da parcela.
   * @return dataVencimento
  **/
  @ApiModelProperty(value = "Data de vencimento da parcela.")
  public String getDataVencimento() {
    return dataVencimento;
  }

  public void setDataVencimento(String dataVencimento) {
    this.dataVencimento = dataVencimento;
  }

  public GetParcelasParcelaResponse PMT(Double PMT) {
    this.PMT = PMT;
    return this;
  }

   /**
   * Código da parcela.
   * @return PMT
  **/
  @ApiModelProperty(value = "Código da parcela.")
  public Double getPMT() {
    return PMT;
  }

  public void setPMT(Double PMT) {
    this.PMT = PMT;
  }

  public GetParcelasParcelaResponse valorSaldoParcela(Double valorSaldoParcela) {
    this.valorSaldoParcela = valorSaldoParcela;
    return this;
  }

   /**
   * Valor do saldo total da parcela.
   * @return valorSaldoParcela
  **/
  @ApiModelProperty(value = "Valor do saldo total da parcela.")
  public Double getValorSaldoParcela() {
    return valorSaldoParcela;
  }

  public void setValorSaldoParcela(Double valorSaldoParcela) {
    this.valorSaldoParcela = valorSaldoParcela;
  }

  public GetParcelasParcelaResponse situacao(SituacaoParcela situacao) {
    this.situacao = situacao;
    return this;
  }

   /**
   * Get situacao
   * @return situacao
  **/
  @ApiModelProperty(value = "")
  public SituacaoParcela getSituacao() {
    return situacao;
  }

  public void setSituacao(SituacaoParcela situacao) {
    this.situacao = situacao;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetParcelasParcelaResponse getParcelasParcelaResponse = (GetParcelasParcelaResponse) o;
    return Objects.equals(this.codigoContrato, getParcelasParcelaResponse.codigoContrato) &&
        Objects.equals(this.valorPago, getParcelasParcelaResponse.valorPago) &&
        Objects.equals(this.numeroParcela, getParcelasParcelaResponse.numeroParcela) &&
        Objects.equals(this.dataPagamento, getParcelasParcelaResponse.dataPagamento) &&
        Objects.equals(this.operador, getParcelasParcelaResponse.operador) &&
        Objects.equals(this.NSU, getParcelasParcelaResponse.NSU) &&
        Objects.equals(this.dataVencimento, getParcelasParcelaResponse.dataVencimento) &&
        Objects.equals(this.PMT, getParcelasParcelaResponse.PMT) &&
        Objects.equals(this.valorSaldoParcela, getParcelasParcelaResponse.valorSaldoParcela) &&
        Objects.equals(this.situacao, getParcelasParcelaResponse.situacao);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigoContrato, valorPago, numeroParcela, dataPagamento, operador, NSU, dataVencimento, PMT, valorSaldoParcela, situacao);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetParcelasParcelaResponse {\n");
    
    sb.append("    codigoContrato: ").append(toIndentedString(codigoContrato)).append("\n");
    sb.append("    valorPago: ").append(toIndentedString(valorPago)).append("\n");
    sb.append("    numeroParcela: ").append(toIndentedString(numeroParcela)).append("\n");
    sb.append("    dataPagamento: ").append(toIndentedString(dataPagamento)).append("\n");
    sb.append("    operador: ").append(toIndentedString(operador)).append("\n");
    sb.append("    NSU: ").append(toIndentedString(NSU)).append("\n");
    sb.append("    dataVencimento: ").append(toIndentedString(dataVencimento)).append("\n");
    sb.append("    PMT: ").append(toIndentedString(PMT)).append("\n");
    sb.append("    valorSaldoParcela: ").append(toIndentedString(valorSaldoParcela)).append("\n");
    sb.append("    situacao: ").append(toIndentedString(situacao)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

