/*
 * Gestão de Contratos
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.GetParcelasParcelaResponse;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Entidade representando uma parcela de um contrato na saida da operação de recuperação de parcelas de um contrato.
 */
@ApiModel(description = "Entidade representando uma parcela de um contrato na saida da operação de recuperação de parcelas de um contrato.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-16T17:43:45.741Z")
public class GetParcelasResponse {
  @SerializedName("parcelas")
  private List<GetParcelasParcelaResponse> parcelas = null;

  public GetParcelasResponse parcelas(List<GetParcelasParcelaResponse> parcelas) {
    this.parcelas = parcelas;
    return this;
  }

  public GetParcelasResponse addParcelasItem(GetParcelasParcelaResponse parcelasItem) {
    if (this.parcelas == null) {
      this.parcelas = new ArrayList<GetParcelasParcelaResponse>();
    }
    this.parcelas.add(parcelasItem);
    return this;
  }

   /**
   * Get parcelas
   * @return parcelas
  **/
  @ApiModelProperty(value = "")
  public List<GetParcelasParcelaResponse> getParcelas() {
    return parcelas;
  }

  public void setParcelas(List<GetParcelasParcelaResponse> parcelas) {
    this.parcelas = parcelas;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetParcelasResponse getParcelasResponse = (GetParcelasResponse) o;
    return Objects.equals(this.parcelas, getParcelasResponse.parcelas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parcelas);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetParcelasResponse {\n");
    
    sb.append("    parcelas: ").append(toIndentedString(parcelas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

