/*
 * Gestão de Contratos
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Enumeration das situações de uma parcela.
 */
@JsonAdapter(SituacaoParcela.Adapter.class)
public enum SituacaoParcela {
  
  ABERTA("ABERTA"),
  
  LIQUIDADA("LIQUIDADA"),
  
  CANCELADA("CANCELADA");

  private String value;

  SituacaoParcela(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SituacaoParcela fromValue(String text) {
    for (SituacaoParcela b : SituacaoParcela.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<SituacaoParcela> {
    @Override
    public void write(final JsonWriter jsonWriter, final SituacaoParcela enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SituacaoParcela read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SituacaoParcela.fromValue(String.valueOf(value));
    }
  }
}

