/*
 * Gestão de Contratos
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Entidade representando a entrada da operação de solicitação de pagamentos.
 */
@ApiModel(description = "Entidade representando a entrada da operação de solicitação de pagamentos.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-16T17:43:45.741Z")
public class SolicitacaoPagamentoRequest {
  @SerializedName("quantidadeParcelas")
  private Integer quantidadeParcelas = null;

  @SerializedName("valorPagamento")
  private Double valorPagamento = null;

  @SerializedName("operador")
  private String operador = null;

  public SolicitacaoPagamentoRequest quantidadeParcelas(Integer quantidadeParcelas) {
    this.quantidadeParcelas = quantidadeParcelas;
    return this;
  }

   /**
   * Quantidade de parcelas a serem pagas.
   * @return quantidadeParcelas
  **/
  @ApiModelProperty(value = "Quantidade de parcelas a serem pagas.")
  public Integer getQuantidadeParcelas() {
    return quantidadeParcelas;
  }

  public void setQuantidadeParcelas(Integer quantidadeParcelas) {
    this.quantidadeParcelas = quantidadeParcelas;
  }

  public SolicitacaoPagamentoRequest valorPagamento(Double valorPagamento) {
    this.valorPagamento = valorPagamento;
    return this;
  }

   /**
   * Valor do pagamento a ser solicitado.
   * @return valorPagamento
  **/
  @ApiModelProperty(value = "Valor do pagamento a ser solicitado.")
  public Double getValorPagamento() {
    return valorPagamento;
  }

  public void setValorPagamento(Double valorPagamento) {
    this.valorPagamento = valorPagamento;
  }

  public SolicitacaoPagamentoRequest operador(String operador) {
    this.operador = operador;
    return this;
  }

   /**
   * Código do operador.
   * @return operador
  **/
  @ApiModelProperty(value = "Código do operador.")
  public String getOperador() {
    return operador;
  }

  public void setOperador(String operador) {
    this.operador = operador;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SolicitacaoPagamentoRequest solicitacaoPagamentoRequest = (SolicitacaoPagamentoRequest) o;
    return Objects.equals(this.quantidadeParcelas, solicitacaoPagamentoRequest.quantidadeParcelas) &&
        Objects.equals(this.valorPagamento, solicitacaoPagamentoRequest.valorPagamento) &&
        Objects.equals(this.operador, solicitacaoPagamentoRequest.operador);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quantidadeParcelas, valorPagamento, operador);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SolicitacaoPagamentoRequest {\n");
    
    sb.append("    quantidadeParcelas: ").append(toIndentedString(quantidadeParcelas)).append("\n");
    sb.append("    valorPagamento: ").append(toIndentedString(valorPagamento)).append("\n");
    sb.append("    operador: ").append(toIndentedString(operador)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

