/*
 * Gestão de Contratos
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SolicitacaoPagamentoParcelaResponse;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Entidade representando a saida da operação de solicitação de pagamentos.
 */
@ApiModel(description = "Entidade representando a saida da operação de solicitação de pagamentos.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-16T17:43:45.741Z")
public class SolicitacaoPagamentoResponse {
  @SerializedName("NSU")
  private String NSU = null;

  @SerializedName("dataPagamento")
  private String dataPagamento = null;

  @SerializedName("comprovantePagamento")
  private String comprovantePagamento = null;

  @SerializedName("nomeCliente")
  private String nomeCliente = null;

  @SerializedName("cpfCliente")
  private String cpfCliente = null;

  @SerializedName("parcelas")
  private List<SolicitacaoPagamentoParcelaResponse> parcelas = null;

  public SolicitacaoPagamentoResponse NSU(String NSU) {
    this.NSU = NSU;
    return this;
  }

   /**
   * Número sequencial único.
   * @return NSU
  **/
  @ApiModelProperty(value = "Número sequencial único.")
  public String getNSU() {
    return NSU;
  }

  public void setNSU(String NSU) {
    this.NSU = NSU;
  }

  public SolicitacaoPagamentoResponse dataPagamento(String dataPagamento) {
    this.dataPagamento = dataPagamento;
    return this;
  }

   /**
   * Data do pagamento.
   * @return dataPagamento
  **/
  @ApiModelProperty(value = "Data do pagamento.")
  public String getDataPagamento() {
    return dataPagamento;
  }

  public void setDataPagamento(String dataPagamento) {
    this.dataPagamento = dataPagamento;
  }

  public SolicitacaoPagamentoResponse comprovantePagamento(String comprovantePagamento) {
    this.comprovantePagamento = comprovantePagamento;
    return this;
  }

   /**
   * Comprovante do pagamento.
   * @return comprovantePagamento
  **/
  @ApiModelProperty(value = "Comprovante do pagamento.")
  public String getComprovantePagamento() {
    return comprovantePagamento;
  }

  public void setComprovantePagamento(String comprovantePagamento) {
    this.comprovantePagamento = comprovantePagamento;
  }

  public SolicitacaoPagamentoResponse nomeCliente(String nomeCliente) {
    this.nomeCliente = nomeCliente;
    return this;
  }

   /**
   * Nome do Cliente.
   * @return nomeCliente
  **/
  @ApiModelProperty(value = "Nome do Cliente.")
  public String getNomeCliente() {
    return nomeCliente;
  }

  public void setNomeCliente(String nomeCliente) {
    this.nomeCliente = nomeCliente;
  }

  public SolicitacaoPagamentoResponse cpfCliente(String cpfCliente) {
    this.cpfCliente = cpfCliente;
    return this;
  }

   /**
   * CPF do Cliente.
   * @return cpfCliente
  **/
  @ApiModelProperty(value = "CPF do Cliente.")
  public String getCpfCliente() {
    return cpfCliente;
  }

  public void setCpfCliente(String cpfCliente) {
    this.cpfCliente = cpfCliente;
  }

  public SolicitacaoPagamentoResponse parcelas(List<SolicitacaoPagamentoParcelaResponse> parcelas) {
    this.parcelas = parcelas;
    return this;
  }

  public SolicitacaoPagamentoResponse addParcelasItem(SolicitacaoPagamentoParcelaResponse parcelasItem) {
    if (this.parcelas == null) {
      this.parcelas = new ArrayList<SolicitacaoPagamentoParcelaResponse>();
    }
    this.parcelas.add(parcelasItem);
    return this;
  }

   /**
   * Get parcelas
   * @return parcelas
  **/
  @ApiModelProperty(value = "")
  public List<SolicitacaoPagamentoParcelaResponse> getParcelas() {
    return parcelas;
  }

  public void setParcelas(List<SolicitacaoPagamentoParcelaResponse> parcelas) {
    this.parcelas = parcelas;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SolicitacaoPagamentoResponse solicitacaoPagamentoResponse = (SolicitacaoPagamentoResponse) o;
    return Objects.equals(this.NSU, solicitacaoPagamentoResponse.NSU) &&
        Objects.equals(this.dataPagamento, solicitacaoPagamentoResponse.dataPagamento) &&
        Objects.equals(this.comprovantePagamento, solicitacaoPagamentoResponse.comprovantePagamento) &&
        Objects.equals(this.nomeCliente, solicitacaoPagamentoResponse.nomeCliente) &&
        Objects.equals(this.cpfCliente, solicitacaoPagamentoResponse.cpfCliente) &&
        Objects.equals(this.parcelas, solicitacaoPagamentoResponse.parcelas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(NSU, dataPagamento, comprovantePagamento, nomeCliente, cpfCliente, parcelas);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SolicitacaoPagamentoResponse {\n");
    
    sb.append("    NSU: ").append(toIndentedString(NSU)).append("\n");
    sb.append("    dataPagamento: ").append(toIndentedString(dataPagamento)).append("\n");
    sb.append("    comprovantePagamento: ").append(toIndentedString(comprovantePagamento)).append("\n");
    sb.append("    nomeCliente: ").append(toIndentedString(nomeCliente)).append("\n");
    sb.append("    cpfCliente: ").append(toIndentedString(cpfCliente)).append("\n");
    sb.append("    parcelas: ").append(toIndentedString(parcelas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

